- generic [ref=e2]:
  - banner [ref=e4]:
    - link "X" [ref=e6] [cursor=pointer]:
      - /url: /
      - img [ref=e7]
  - main [ref=e9]:
    - generic [ref=e12]:
      - button "Back" [ref=e13] [cursor=pointer]:
        - img [ref=e14]
      - heading "Post" [level=2] [ref=e17]
    - article [ref=e20]:
      - generic [ref=e21]:
        - generic [ref=e22]:
          - generic [ref=e23]:
            - link "user avatar" [ref=e26] [cursor=pointer]:
              - /url: https://x.com/RLanceMartin
              - img "user avatar" [ref=e27]
            - generic [ref=e29]:
              - generic [ref=e30]:
                - generic [ref=e31]:
                  - link "Lance Martin" [ref=e32] [cursor=pointer]:
                    - /url: https://x.com/RLanceMartin
                  - button "Verified account" [ref=e36] [cursor=pointer]:
                    - img [ref=e37]
                - link "@RLanceMartin" [ref=e40] [cursor=pointer]:
                  - /url: https://x.com/RLanceMartin
              - button "More" [ref=e42] [cursor=pointer]:
                - img [ref=e43]
          - generic [ref=e45]:
            - link "Article cover image Article Designing loops with Fable 5 Mythos-class models like Claude Fable 5 have changed the way many of us work at Anthropic. I want to share two tips for getting the most out of this class of models. Self-correction loops There’s been..." [ref=e46] [cursor=pointer]:
              - /url: /i/article/2064380553919676416
              - generic [ref=e47]:
                - img "Article cover image" [ref=e49]
                - img "Article" [ref=e50]:
                  - generic [ref=e51]:
                    - img [ref=e52]
                    - text: Article
              - generic [ref=e54]:
                - generic [ref=e55]: Designing loops with Fable 5
                - generic [ref=e56]: Mythos-class models like Claude Fable 5 have changed the way many of us work at Anthropic. I want to share two tips for getting the most out of this class of models. Self-correction loops There’s been...
            - generic [ref=e57]:
              - link "5:21 PM · Jun 9, 2026" [ref=e59] [cursor=pointer]:
                - /url: /RLanceMartin/status/2064397389189071163
              - generic [ref=e60]:
                - text: ·
                - link "1.3M Views" [ref=e61] [cursor=pointer]:
                  - /url: https://x.com/RLanceMartin/status/2064397389189071163
                  - generic [ref=e62]: 1.3M
                  - generic [ref=e63]: Views
        - generic [ref=e65]:
          - generic [ref=e67]:
            - button "Reply" [ref=e68] [cursor=pointer]:
              - img [ref=e69]
            - button "76" [ref=e71] [cursor=pointer]:
              - img "76" [ref=e73]:
                - generic [ref=e75]:
                  - generic [ref=e76]: "7"
                  - generic [ref=e77]: "6"
          - generic [ref=e79]:
            - button "Repost" [ref=e80] [cursor=pointer]:
              - img [ref=e81]
            - button "548" [ref=e83] [cursor=pointer]:
              - img "548" [ref=e85]:
                - generic [ref=e87]:
                  - generic [ref=e88]: "5"
                  - generic [ref=e89]: "4"
                  - generic [ref=e90]: "8"
          - generic [ref=e92]:
            - button "Like" [ref=e93] [cursor=pointer]:
              - img [ref=e94]
            - button "4524" [ref=e96] [cursor=pointer]:
              - img "4.5K" [ref=e98]:
                - generic [ref=e99]:
                  - generic [ref=e101]: "4"
                  - generic [ref=e102]:
                    - generic [ref=e103]: .
                    - generic [ref=e104]: "5"
                - generic [ref=e106]: K
          - generic [ref=e108]:
            - button "Bookmark" [ref=e109] [cursor=pointer]:
              - img [ref=e110]
            - button "11740" [ref=e112] [cursor=pointer]:
              - img "12K" [ref=e114]:
                - generic [ref=e116]:
                  - generic [ref=e117]: "1"
                  - generic [ref=e118]: "2"
                - generic [ref=e120]: K
          - button "Share" [ref=e121] [cursor=pointer]:
            - img [ref=e122]
        - button "Read 76 replies" [ref=e124] [cursor=pointer]:
          - generic [ref=e125]:
            - img [ref=e126]
            - generic [ref=e128]: Read 76 replies
  - complementary [ref=e129]:
    - generic [ref=e131]:
      - generic [ref=e132]:
        - heading "New to X?" [level=2] [ref=e133]
        - generic [ref=e134]:
          - paragraph [ref=e135]: Sign up now to get your own personalized timeline!
          - generic [ref=e136]:
            - button "Sign up with Google" [disabled] [ref=e137]:
              - img [ref=e138]
              - text: Sign up with Google
            - button "Sign up with Apple" [disabled] [ref=e143]:
              - img [ref=e144]
              - text: Sign up with Apple
            - link "Create account" [ref=e146] [cursor=pointer]:
              - /url: /i/jf/onboarding/web?mode=signup
          - paragraph [ref=e147]:
            - text: By signing up, you agree to the
            - link "Terms of Service" [ref=e148] [cursor=pointer]:
              - /url: https://x.com/tos
            - text: and
            - link "Privacy Policy" [ref=e149] [cursor=pointer]:
              - /url: https://x.com/privacy
            - text: ", including"
            - link "Cookie Use." [ref=e150] [cursor=pointer]:
              - /url: https://support.x.com/articles/20170514
      - generic [ref=e151]:
        - heading "Relevant people" [level=2] [ref=e152]
        - generic [ref=e154]:
          - link "user avatar" [ref=e155] [cursor=pointer]:
            - /url: https://x.com/RLanceMartin
            - img "user avatar" [ref=e156]
          - generic [ref=e158]:
            - link "Lance Martin @RLanceMartin" [ref=e159] [cursor=pointer]:
              - /url: /RLanceMartin
              - generic [ref=e160]: Lance Martin
              - generic [ref=e161]: "@RLanceMartin"
            - link "Follow" [ref=e162] [cursor=pointer]:
              - /url: /i/jf/onboarding/web?mode=login&redirect_after_login=%2FRLanceMartin
      - generic [ref=e163]:
        - heading "Trending now" [level=2] [ref=e164]
        - img [ref=e168]
      - navigation "Footer" [ref=e171]:
        - generic [ref=e172]:
          - link "Terms of Service" [ref=e173] [cursor=pointer]:
            - /url: https://x.com/tos
          - generic [ref=e174]: "|"
        - generic [ref=e175]:
          - link "Privacy Policy" [ref=e176] [cursor=pointer]:
            - /url: https://x.com/privacy
          - generic [ref=e177]: "|"
        - generic [ref=e178]:
          - link "Cookie Policy" [ref=e179] [cursor=pointer]:
            - /url: https://support.x.com/articles/20170514
          - generic [ref=e180]: "|"
        - generic [ref=e181]:
          - link "Accessibility" [ref=e182] [cursor=pointer]:
            - /url: https://help.x.com/resources/accessibility
          - generic [ref=e183]: "|"
        - generic [ref=e184]:
          - link "Ads info" [ref=e185] [cursor=pointer]:
            - /url: https://business.x.com/en/help/troubleshooting/how-twitter-ads-work.html?ref=web-twc-ao-gbl-adsinfo&utm_source=twc&utm_medium=web&utm_campaign=ao&utm_content=adsinfo
          - generic [ref=e186]: "|"
        - button "More" [ref=e187] [cursor=pointer]:
          - text: More
          - img [ref=e188]
        - generic [ref=e190]: © 2026 X Corp.
  - generic [ref=e193]:
    - generic [ref=e194]:
      - generic [ref=e195]: Don't miss what's happening
      - generic [ref=e196]: People on X are the first to know.
    - generic [ref=e197]:
      - link "Log in" [ref=e198] [cursor=pointer]:
        - /url: /i/jf/onboarding/web?mode=login
      - link "Sign up" [ref=e199] [cursor=pointer]:
        - /url: /i/jf/onboarding/web?mode=signup